### ISSUE TITLE
Kinozal is not available

### ISSUE THREAD

**Issue by ScreNN** [Prowlarr/Prowlarr#1037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Indexer Kinozal is not available over five days. Just stopped working. Sometimes connects but then falls off again
The Jackett Kinozal works well

### Expected Behavior

Worked fine five days ago

### Environment

```markdown
- OS: Unraid
- Prowlarr: 0.4.0.1816
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox
```

### What branch are you running?

Develop

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/8920238/prowlarr.trace.txt)

![QpRQiRaFaf](https://user-images.githubusercontent.com/13724242/174109342-cbb1ca95-2c74-4792-b5f3-de0011e387c5.png)

[[AB#3294](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3294)]

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

Exceptions are not bugs.

> [v0.3.0.1730] System.Net.WebException: The operation has timed out.: 'http://kinozal.tv/browse.php?c=0&s=&g=0&v=0&d=0&w=0&t=0&f=0'


- your system cannot connect to the tracker due to an issue with your system, not Prowlarr.  Timeouts are typically due to broken dns, broken ipv6, or VPN/proxy issues.
- our definition  matches jackett / jackett's definition has not been changed in months.
