### ISSUE TITLE
Disable Authentication

### ISSUE THREAD

**Issue by mateuszkozakiewicz** [Prowlarr/Prowlarr#1265]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Since 1.0.0 Prowlarr requires user/password auth. This is not in line with other *arr apps and forces a specific auth method.

### Describe the solution you'd like

Possibility to disable user/password authentication by the user for example in case authentication is handled externally.

### Describe alternatives you've considered

Alternatively give possibility to include IP CIDR which should not be asked for user/password, this would be useful in setups where Prowlarr is behind known reverse proxy which already provides auth method.

### Anything else?

Thanks

[AB#4562](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4562)

**Comment by Roxedus** [comment]
This is in line with all the other arrs, they just havent reached master yet. 
Check the wiki. https://wiki.servarr.com/prowlarr/faq#can-i-disable-forced-authentication

**Comment by mateuszkozakiewicz** [comment]
Indeed my bad, may I ask why this is not possible from the UI?

**Comment by Roxedus** [comment]
Because it should not be easy to run with no security (in arrs eyes)

**Comment by bakerboy448** [comment]
> Possibility to disable user/password authentication by the user for example in case authentication is handled externally.

this exists. See the FAQ. No plans to remove the forced auth.

**Comment by traverseda** [comment]
> > Possibility to disable user/password authentication by the user for example in case authentication is handled externally.
> 
> this exists. See the FAQ. No plans to remove the forced auth.

Any chance we can turn this into an environment variable? Would make getting set up in docker a whole lot easier, rather than requiring users to go in and manually edit the config file I could just have one docker compose file that sets up the *arr's and an appropriate reverse proxy.

Alternatively perhaps some header we could pass? I'd quite prefer an env variable, but if you're insistent on making this hard to do...

**Comment by bakerboy448** [comment]
You don't need to edit the config file to start;
you can pre-create it with auth set to external and the xml header and radarr will fill in the missing attributes as applicable.

env var are covered under https://github.com/Prowlarr/Prowlarr/issues/777

**Comment by traverseda** [comment]
I can't do that in portainer, using a default linuxserver.io image. What you're asking me to do is maintain a complete set of replacement customized docker images instead of what was once a pretty simple compose file.

Or you're asking me to trust some internet person who comes up with a forked docker image that doesn't force external auth, instead of the upstream sources.

Neither are really ideal, I mean I'm technical enough that I can just ssh in and edit the config file (despite the path being a bit unclear as it's a docker volume that points to a remote CIFS server), but I'm hearing that I'm going to have to do that for every *arr service in the future, and if I want to start fresh I'm going to have to do that for every *arr service later on? And I'll need to do it again if I want to create a mini *arr stack on an rpi or something, or if I want to share my portainer templates with anyone else I'll need to mention "hey by the way you need to figure out where the raw config file is on all these individual apps and run this command".

Essentially what this means is that nobody down stream can bundle this with a reverse proxy in the future, and I think that's a pretty big mistake from a usability perspective. It won't effect the highly technical users, but it will prevent simple templates from being copy+pasted into portainer or yacht or similar container management tools.

**Comment by traverseda** [comment]
This is what my current *arr deployment looks like, it's pretty simple and doesn't require me to build any docker images. Since most apps are at least moderately [12 factor](https://12factor.net/) compatible I don't need to edit any files and if I suddenly wiped out all my *arr configs I'd still end up with a working (although not customized) install. One docker compose file, complete stack with downloaders, authenticating reverse proxy, and *arr services, that works out of the box.

Not being able to disable auth completely breaks single sign on. If you really really want to make it hard to disable auth you could have one option be a single-sign-on provider, like an oauth provider?

![image](https://user-images.githubusercontent.com/2125828/216092027-ebbb0806-0b08-4c71-b2af-e43f7ef5bc7b.png)

**Comment by thezak48** [comment]
The issue being is we don't provide 1st party docker images so having the auth setting to be controllable via a environment variable is not possible iirc

**Comment by mateuszkozakiewicz** [comment]
> The issue being is we don't provide 1st party docker images so having the auth setting to be controllable via a environment variable is not possible iirc

I am not sure how one prevents the other?env vars are not docker or even system specific mechanism

**Comment by traverseda** [comment]
>Also your docker paths so not allow for hardlinking or atomic moves

That's what remote path mappings are for, and I do have those configured (manually) where I need them. Thanks for the concern though. I'm not suggesting that my deployment is perfect, and I'm not sharing it with anyone at the moment, but the point is that it is only one docker compose file to get everything functional with single-sign-on.

>The issue being is we don't provide 1st party docker images so having the auth setting to be controllable via a environment variable is not possible iirc

I don't understand how that would effect anything. Environment variables are just environment variables. You can check to see if one is set pretty much anywhere. I was actually suggesting checking an environment variable to see if you should force the user to set an auth method via the UI.

**Comment by thezak48** [comment]
Yeah true I like just woke up 😅 , Rather then cluttering this closed issue up. I suggest you make a new feature request for setting auth via env's

**Comment by traverseda** [comment]
I'd rather not just open another "disable authentication" issue without a better understanding of why this one was closes as wontfix in the first place. I've made my case, I've explained why this really is an issue, for what I imagine is a not uncommon deployment. Of course prowlarr devs probably have better insight into that since they collect usage statistics.

Basically I'd encourage them to check how many sonarr instances are running in docker behind a reverse proxy, and consider that said reverse proxy may very well be doing some form of single-sign-on.

**Comment by thezak48** [comment]
I am not saying open another "disable authentication" issue, I am saying open a "allow auth to be set via env" feature request.

The reason why this was closed to begin with was it was asking to allow auth to be disabled via the UI which we won't do 
> Because it should not be easy to run with no security

We are forcing Auth at the request of the major indexers, it is a case of do this or we will ban the arr's out right because users just seem to like opening their arr's up to the internet with no authentication in place. All arr's will be forcing auth very soon in their new versions

**Comment by thezak48** [comment]
OIDC is a database setting iirc

**Comment by RobinDadswell** [comment]
> OIDC is a database setting iirc

Yes the current implementation of OIDC is a database setting and so not configurable via environment variable. This is not likely to change based on recent conversations we have had within the development team about this.

**Comment by traverseda** [comment]
> OIDC is a database setting iirc
> 
> Also did I read that right that the config folder is stored on a network share? if so I hope you enjoy the corruption fun times sweat_smile

Once again, I appreciate the concern but it has not been an issue in the several years I've been using this setup. There are various CIFS mounts options depending on if you want performance or more robust locking, and while I'm sure it's easy to configure in a way that causes corruption it's also pretty easy to not do that. It might horrify you to know that the CIFS share is actually sharing a mergerfs filesystem, with bcache thrown in there just for fun. Also inline file compression.

>Yes the current implementation of OIDC is a database setting and so not configurable via environment variable. This is not likely to change based on recent conversations we have had within the development team about this.

Well that's unfortunate, but it's not the hill I'm going to die on.

It would be nice if the development team gave some though on how to do single-sign-on in a 12factor compatible way, but at the moment I don't have any solid technical recommendations on how to accomplish that with your architecture. I probably will take the route of forking the docker images for my own infra when the time comes.
