### ISSUE TITLE
Query from sonarr does not match prowlarr query

### ISSUE THREAD

**Issue by GerhardtBruwer** [Prowlarr/Prowlarr#1514]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I’ve only experienced this issue in a very specific case, granted, the name is a bit strange when compared with other media. Here are some logs

sonarr 
`2023-03-06 14:08:14.3|Info|ReleaseSearchService|Searching indexers for [NieR:Automata Ver1.1a : S01E01 (01)]. 2 active indexers
2023-03-06 14:08:14.8|Info|DownloadDecisionMaker|No results found `
Note the show name query.

Then prowlarr:
`2023-03-06 14:08:14.3|Info|ReleaseSearchService|Searching indexer(s): [IPTorrents] for Term: [NieR Automata Ver11a 01], Offset: 0, Limit: 100, Categories: [5070]
2023-03-06 14:08:14.3|Info|ReleaseSearchService|Searching indexer(s): [NzbPlanet] for Term: [NieR Automata Ver11a 01], Offset: 0, Limit: 100, Categories: [5070] `

So the query loses the period when received prowlarr side. When I add my indexers directly to sonarr it behaves as expected.

A worthy mention, if I edit the search term in prowlarr manually, results are returned, so the issue seems to be that somewhere along the way the period gets replaced. This is a bit of a rare case, but might happen with other weirdly named shows.

### Expected Behavior

The query should remain the same from sonarr to prowlarr. I reckon this should be checked from any source. Period should remain in the query / search term if sent as such from sonarr / radar.

### Steps To Reproduce

1. Add your torrent / nzb indexers to prowlarr 
2. Connect to sonarr
3. Add NieR:Automata ver1.1a as a show and search for an episode then view logs. Take note of the query.
4. Open up the prowlarr webUI, view logs and have a look at the query.

On prowlarr the period is removed to become `NieR Automata ver11a`.

### Environment

```markdown
- OS: Unraid
- Prowlarr: v 1.2.2.2699
- Docker Install: yes
- Using Reverse Proxy: no
```
In this case unraid is possibly not relevant, since I can negate the issue by adding my indexers to sonarr directly.

### What branch are you running?

Master

### Trace Logs?

sonarr 
`2023-03-06 14:08:14.3|Info|ReleaseSearchService|Searching indexers for [NieR:Automata Ver1.1a : S01E01 (01)]. 2 active indexers
2023-03-06 14:08:14.8|Info|DownloadDecisionMaker|No results found `
Note the show name query.

prowlarr:
`2023-03-06 14:08:14.3|Info|ReleaseSearchService|Searching indexer(s): [IPTorrents] for Term: [NieR Automata Ver11a 01], Offset: 0, Limit: 100, Categories: [5070]
2023-03-06 14:08:14.3|Info|ReleaseSearchService|Searching indexer(s): [NzbPlanet] for Term: [NieR Automata Ver11a 01], Offset: 0, Limit: 100, Categories: [5070] `

**Comment by bakerboy448** [comment]
1) The log lines you are looking at are informational to what is searched and does not reflect how it is searched.
 2) See sonarr's troubleshooting article for more information

**Comment by GerhardtBruwer** [comment]
Cool, will read how to get better logs In the morning then add them to the ticket. Does it matter that it’s been marked as closed?

Reason why I logged this as a bug is because it works for most cases, just this one so far seems to misbehave - was a bug ticket the right call?

**Comment by Maronato** [comment]
I'm having the same issue, and it does appear to be a bug. When using Sonarr to search for the same series (`NieR:Automata Ver1.1a`), Prowlarr strips the period only for **some** indexers.

Nyaa works fine and uses the period, but other indexers such as AnimeTosho receive the request from Prowlarr without it.

The fact that Sonarr doesn't know what the actual indexers are, since it's searching via Prowlarr/Torznab, and that one of the indexers works (Nyaa), leads me to believe the issue is in Prowlarr.

I also considered the possibility that Nyaa too is receiving the request without the period, but making the request directly from within Prowlarr without it yields zero results.

IMO this should be reopened and possibly relabeled to either `type:bug` or `type:external bug` if we can show it's a sonarr issue.

**Comment by bakerboy448** [comment]
> Prowlarr strips the period only for some indexers.

that's expected.
1) certain sites support RawSearch thus sonarr sends a differently formatted query
2) sites need various massaging of their terms due to specific site nuances

> The fact that Sonarr doesn't know what the actual indexers are, since it's searching via Prowlarr/Torznab, and that one of the indexers works (Nyaa), leads me to believe the issue is in Prowlarr.

not an issue at all and what the site is named has no impact on what sonarr does.   The capabilities ("caps") does.  These are configured for each indexer in prowlarr as part of its definition

> I also considered the possibility that Nyaa too is receiving the request without the period, but making the request directly from within Prowlarr without it yields zero results.

prowlarr logs will show you the exact url / query to the site 

> this should be reopened and possibly relabeled to either type:bug or type:external bug if we can show it's a sonarr issue.

not a prowlarr bug
Not a sonarr bug

again, for support issues use the support methods.

again, see sonarr's troubleshooting docs for details - this is an common problem noted in the docs.
