### ISSUE TITLE
[BUG]: Kinozal parsing is broken

### ISSUE THREAD

**Issue by dm3ch** [Prowlarr/Prowlarr#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1226" alt="Screenshot 2021-09-08 at 00 11 59" src="https://user-images.githubusercontent.com/5025313/132411683-bf289dc9-10d8-47ac-8284-84b05ad5cc4d.png">

Currently Kinozal indexer provides broken titles and and wrong info about release size.
If I right remember this indexer worked fine in the end of 2021 July.

At the same time this indexer works perfectly in Jackett right now.

### Expected Behavior

Indexer parsing works fine.

### Steps To Reproduce

1) Add kinozal indexer
2) Perform search

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr: 0.1.1.875
- Docker Install: yes - 0.1.1.875-ls17 by linuxserver.io
- Using Reverse Proxy: Yes (traefik)
- Browser: Chrome Version 92.0.4515.159 (Official Build) (x86_64)
```

### What branch are you running?

Develop

### Anything else?

[prowlarr.log](https://github.com/Prowlarr/Prowlarr/files/7124398/prowlarr.log)

[AB#1569](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1569)

**Comment by bakerboy448** [comment]
likely mostly fixed by https://github.com/Prowlarr/Indexers/pull/36 - this is the prowlarr definition, but updated off recent jackett changes

you can confirm this real quick:
- download this file (the updated YML from the PR) https://raw.githubusercontent.com/Prowlarr/Indexers/b603dc0837769853657e6d43f2a1e8b98aa445d6/definitions/v1/kinozal.yml
- change the filename and the id & name within the file as follows:
  - filename: `kinozal-local.yml`
  - id: `kinozal-local`
  - name: `kinozal-local`
- Save this new yml to the Custom definition folder (https://wiki.servarr.com/prowlarr/indexers#adding-a-custom-yml-definition)
- Add it to prowlarr and check a search

**Comment by dm3ch** [comment]
I just have tested. Still broken

**Comment by dm3ch** [comment]
Checked definition, it seems that Age and Size parsing could be also broken due to problem with cyrillic symbols.

Is it possible that encoding conversation was broken in Prowlarr? Cause indexer still works fine on Jackett.

**Comment by Qstick** [comment]
I'd need an invite to test

**Comment by dm3ch** [comment]
> I'd need an invite to test

Kinozal is semi-private indexer, so you can register without invite using this URL: http://kinozal.tv/signup.php

**Comment by Qstick** [comment]
Thanks for the report, should be fixed now in next nightly 
![image](https://user-images.githubusercontent.com/376117/142564625-8969861a-4dec-4baa-9b81-ef926a27276c.png)
