### ISSUE TITLE
[FEAT]: Libgen integration

### ISSUE THREAD

**Issue by almottier** [Prowlarr/Prowlarr#510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Library Genesis (libgen) is the most complete ebook collection. It would be nice if you could add it to Prowlarr to be able to use it with Readarr.

### Describe the solution you'd like

Libgen integration

### Describe alternatives you've considered

- LazyLibrarian has libgen integration but I prefer Readarr/Prowlarr which are more modern. 
- [Libgen Readarr integration](https://github.com/Readarr/Readarr/issues/848#issuecomment-921981231)

### Anything else?

https://libgen.onl/

[AB#1597](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1597)

**Comment by Qstick** [comment]
No plans to have Prowlarr direct download anything. So in order to pull this off we would need to hook to a downloader as well, In addition Prowlarr would have to function/mask itself as a download client to Readarr. At that point we could spoof the indexer as a newznab indexer to Readarr from Prowlarr and then have downloads called by Readarr route thru Prowlarr and to the downloader. It's quite a bit of work pulling this off but doable for sure.

**Comment by sdfg2** [comment]
I've been tracking this issue and https://github.com/Readarr/Readarr/issues/848 over at Readarr, and I might be missing something but it looks like in the Readarr issue they have links to NZB and torrents for libgen which could be added to Prowlarr so that Prowlarr doesn't have to worry about direct downloading or dealing with download clients or anything like that?

**Comment by Qstick** [comment]
> I've been tracking this issue and https://github.com/Readarr/Readarr/issues/848 over at Readarr, and I might be missing something but it looks like in the Readarr issue they have links to NZB and torrents for libgen which could be added to Prowlarr so that Prowlarr doesn't have to worry about direct downloading or dealing with download clients or anything like that?

The torrent links we can likely work with, looks like the nzbs are rar'd so not sure I want to screw with it.

**Comment by kimcosmos** [comment]
each torrent is a collection of 1000s of books. Do you have a way to selectively download? Their preferred method now is IPFS via cloudflare or their database app

**Comment by bakerboy448** [comment]
- No plans for prowlarr to support DDLs
- Appears no easy route for torrents to be usable as they'd need to have individual pieces selected
