### ISSUE TITLE
[FEAT]: Add Support for using MyAnonamouse freeleech tokens

### ISSUE THREAD

**Issue by jeff47** [Prowlarr/Prowlarr#518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I noticed that for several indexers, we are able to use our FL tokens - for example, on Redacted.  Is there a way to get this working for MAM?  Like many people, I have hundreds of FL tokens but they don't get used unless I download manually.

### Describe the solution you'd like

Similar to Redacted, add option to use FL tokens.  (might not be possible, if it's something that must be implemented on MAM's side.)

### Describe alternatives you've considered

There isn't really an alternative that I know of - I don't believe it's possible to apply a FL token once the torrent file/magnet has been grabbed. 

### Anything else?

Nothing else.  Great work on this project, thanks so much!

[AB#1616](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1616)

**Comment by bakerboy448** [comment]
Based on MAM's API (see below) it does not appear they have a method to trigger the use of a freeleech token (or even search freeleech only on a similarly related note).

@ta264 see anything I'm missing?
----

<table id="mainTable">

<tbody>

<tr>

<td id="mainLeft"></td>

<td id="mainRight">

<div class="blockCon" style="min-width:98%;max-width:98%">

<div class="blockBody">

<div class="blockBodyCon cen" id="mainBody">

<div class="blockCon" style="min-width:950px;max-width:950px">

<div class="blockBody">

<div class="blockBodyCon left">

# Torrent Search (JSON)

## URI: /tor/js/loadSearchJSONbasic.php

### Search torrents

main site search, returning json results (instead of html). This endpoint can accept input via post as application/xml, application/json, multipart/form-data, or application/x-www-form-urlencoded, as well as via get  

<table class="Parameters">

<thead>

<tr>

<th style="width:200px">Parameter</th>

<th>Data type</th>

<th>Additional information</th>

</tr>

</thead>

<tbody>

<tr class="alternateColor">

<td>description</td>

<td>empty</td>

<td>If this parameter is set, it will display the full description field for the torrent.</td>

</tr>

<tr class="alternateColor">

<td>dlLink</td>

<td>blank</td>

<td>show hash for dl link (prepend https://www.myanonamouse.net/tor/download.php/ to use) for downloading on something without a session cookie. Alternatively use session cookie and just hit https://www.myanonamouse.net/tor/download.php?tid=# replacing # with the id number.</td>

</tr>

<tr class="alternateColor">

<td>perpage</td>

<td>int</td>

<td>int in range of 5 to 100, telling how many results to return</td>

</tr>

<tr class="alternateColor">

<td>thumbnail</td>

<td>Set</td>

<td>If this value is set, will return the thumbnail url.</td>

</tr>

<tr class="alternateColor">

<td>tor</td>

<td>array</td>

<td>

### REQUIRED

</td>

</tr>

<tr class="alternateColor">

<td class="indent1">cat</td>

<td>list</td>

<td>List of integers for the categories you wish to view in results</td>

</tr>

<tr class="alternateColor">

<td class="indent1">endDate</td>

<td>date</td>

<td>Date in format YYYY-MM-DD or unix timestamp torrents shoujld have been created before. Exclusive of value provided</td>

</tr>

<tr class="alternateColor">

<td class="indent1">hash</td>

<td>HEX string</td>

<td>Hexadecimal encoded hash from a torrent</td>

</tr>

<tr class="alternateColor">

<td class="indent1">main_cat</td>

<td>array</td>

<td>Array of ID(s) of the main category to include. IDs are:  
13 AudioBooks  
14 E-Books  
15 Musicology  
16 Radio</td>

</tr>

<tr class="alternateColor">

<td class="indent1">searchIn</td>

<td>Enum</td>

<td>list to come</td>

</tr>

<tr class="alternateColor">

<td class="indent1">searchType</td>

<td>enum</td>

<td>'titleAsc': By the Title, Descending order  
'titleDesc': By the Title, Ascending order  
'fileAsc': By number of files, Ascending Order  
'fileDesc': By number of files, Descending Order  
'sizeAsc': By size of the torrent, Ascending Order  
'sizeDesc': By size of the torrent, Descending Order  
'seedersAsc': By number of Seeders, Ascending Order  
'seedersDesc': By number of Seeders, Descending Order  
'leechersAsc': By number of Leechers, Ascending Order  
'leechersDesc': By number of Leechers, Descending Order  
'snatchedAsc': By number of times snatched, Ascending Order  
'snatchedDesc': By number of times snatched, Descending Order  
'dateAsc': By Date Added, Ascending Order  
'dateDesc': By Date Added, Descending Order  
'bmkaAsc': By date bookmarked, Ascending Order (Note: may return odd results if not bookmarked)  
'bmkaDesc': By date bookmarked, Descending Order (Note: may return odd results if not bookmarked)  
'reseedAsc': Date Reseed Request Added, Ascending Order (Note: may return odd results if no reseed request)  
'reseedDesc': Date Reseed Request Added, Descending Order (Note: may return odd results if no reseed request)  
'random': random, duh  
'default':  
    If text search present: by weight DESC, then ID desceding,  
    else if instead searchIn is 'myReseed' or 'allReseed': same as reseedAsc  
    else if searchIn is Bookmarks: same as 'bmkaDesc'  
    else same as 'dateDesc'</td>

</tr>

<tr class="alternateColor">

<td class="indent1">sortType</td>

<td>enum</td>

<td>'titleAsc': By the Title, Descending order  
'titleDesc': By the Title, Ascending order  
'fileAsc': By number of files, Ascending Order  
'fileDesc': By number of files, Descending Order  
'sizeAsc': By size of the torrent, Ascending Order  
'sizeDesc': By size of the torrent, Descending Order  
'seedersAsc': By number of Seeders, Ascending Order  
'seedersDesc': By number of Seeders, Descending Order  
'leechersAsc': By number of Leechers, Ascending Order  
'leechersDesc': By number of Leechers, Descending Order  
'snatchedAsc': By number of times snatched, Ascending Order  
'snatchedDesc': By number of times snatched, Descending Order  
'dateAsc': By Date Added, Ascending Order  
'dateDesc': By Date Added, Descending Order  
'bmkaAsc': By date bookmarked, Ascending Order (Note: may return odd results if not bookmarked)  
'bmkaDesc': By date bookmarked, Descending Order (Note: may return odd results if not bookmarked)  
'reseedAsc': Date Reseed Request Added, Ascending Order (Note: may return odd results if no reseed request)  
'reseedDesc': Date Reseed Request Added, Descending Order (Note: may return odd results if no reseed request)  
'categoryAsc': Sorted by category (number) Ascending, followed by title Ascending  
'categoryDesc': Sorted by category (number) Descending, followed by title Ascending  
'random': random, duh  
'default':  
If text search present: by weight DESC, then ID desceding,  
else if instead searchIn is 'myReseed' or 'allReseed': same as reseedAsc  
else if searchIn is Bookmarks: same as 'bmkaDesc'  
else same as 'dateDesc'</td>

</tr>

<tr class="alternateColor">

<td class="indent1">srchIn</td>

<td>array</td>

<td></td>

</tr>

<tr class="alternateColor">

<td class="indent2">author</td>

<td>Set</td>

<td>If set, will cause the tor[text] to search in the author</td>

</tr>

<tr class="alternateColor">

<td class="indent2">description</td>

<td>Set</td>

<td>If set, will cause the tor[text] to search in the description</td>

</tr>

<tr class="alternateColor">

<td class="indent2">filenames</td>

<td>Set</td>

<td>If set, will cause the tor[text] to search in the filenames</td>

</tr>

<tr class="alternateColor">

<td class="indent2">fileTypes</td>

<td>Set</td>

<td>If set, will cause the tor[text] to search in the file types</td>

</tr>

<tr class="alternateColor">

<td class="indent2">narrator</td>

<td>Set</td>

<td>If set, will cause the tor[text] to search in the narrator</td>

</tr>

<tr class="alternateColor">

<td class="indent2">series</td>

<td>Set</td>

<td>If set, will cause the tor[text] to search in the series</td>

</tr>

<tr class="alternateColor">

<td class="indent2">tags</td>

<td>Set</td>

<td>If set, will cause the tor[text] to search in the tags</td>

</tr>

<tr class="alternateColor">

<td class="indent1">startDate</td>

<td>date</td>

<td>Date in format YYYY-MM-DD or unix timestamp of earliest torrent(s) to show. Inclusive of the provided value</td>

</tr>

<tr class="alternateColor">

<td class="indent1">startNumber</td>

<td>Int</td>

<td>Number of entries to skip. Used in pagination.</td>

</tr>

<tr class="alternateColor">

<td class="indent1">text</td>

<td>text</td>

<td>Text to search for.</td>

</tr>

</tbody>

</table>

### Example input

<pre>application/x-www-form-urlencoded:
tor%5Bcat%5D%5B%5D=0&tor%5BsortType%5D=default&tor%5BbrowseStart%5D=true&tor%5BstartNumber%5D=0&bannerLink&bookmarks&dlLink&description&tor%5Btext%5D=mp3%20m4a

JSON:

{
	"tor": {
		"text": "collection cookbooks food test kitchen",
		"srchIn": {
			"title": "true",
			"author": "true",
			"narrator": "true"
		},
		"searchType": "all",
		"searchIn": "torrents",
		"cat": ["0"],
		"browseFlagsHideVsShow": "0",
		"startDate": "",
		"endDate": "",
		"hash": "",
		"sortType": "default",
		"startNumber": "0"
	},
	"thumbnail": "true"
}</pre>

### Output Parameters

<table class="Parameters">

<thead>

<tr>

<th style="width:200px">Parameter</th>

<th>Data type</th>

<th>Additional information</th>

</tr>

</thead>

<tbody>

<tr class="alternateColor">

<td>data</td>

<td>List</td>

<td>This is a list of objects/arrays with the following keys</td>

</tr>

<tr class="alternateColor">

<td class="indent1">added</td>

<td>datetime</td>

<td>the date and time (in utc) the item was uploaded to site</td>

</tr>

<tr class="alternateColor">

<td class="indent1">author_info</td>

<td>string</td>

<td>json object of id:name pairs</td>

</tr>

<tr class="alternateColor">

<td class="indent1">bookmarked</td>

<td>datetime (nullable)</td>

<td>Datetime of when an item was bookmarked by the user (or null if not bookmarked)</td>

</tr>

<tr class="alternateColor">

<td class="indent1">browseflags</td>

<td>bitfield</td>

<td>bit field of the different tags and flags on a torrent see [link pending] for more information</td>

</tr>

<tr class="alternateColor">

<td class="indent1">cat</td>

<td>string</td>

<td>the html display for the category based on the users preferences</td>

</tr>

<tr class="alternateColor">

<td class="indent1">category</td>

<td>int</td>

<td>specific category id the item is in</td>

</tr>

<tr class="alternateColor">

<td class="indent1">catname</td>

<td>string</td>

<td>the category the item is in</td>

</tr>

<tr class="alternateColor">

<td class="indent1">comments</td>

<td>int</td>

<td>number of comments users have added to the item</td>

</tr>

<tr class="alternateColor">

<td class="indent1">dl</td>

<td>string</td>

<td>user specific hash to download the torrent file. You can download by appending it to the url: /tor/download.php/</td>

</tr>

<tr class="alternateColor">

<td class="indent1">filetypes</td>

<td>string</td>

<td>concatenated string of file types</td>

</tr>

<tr class="alternateColor">

<td class="indent1">fl_vip</td>

<td>boolean</td>

<td>if the item is freeleech and/or vip</td>

</tr>

<tr class="alternateColor">

<td class="indent1">free</td>

<td>boolean</td>

<td>if the item is freeleech or not</td>

</tr>

<tr class="alternateColor">

<td class="indent1">id</td>

<td>int</td>

<td>the id of the torrent itself. User can pull up the page via /t/{id}</td>

</tr>

<tr class="alternateColor">

<td class="indent1">lang_code</td>

<td>string</td>

<td>the 3 letter ISO code for the language</td>

</tr>

<tr class="alternateColor">

<td class="indent1">language</td>

<td>int</td>

<td>the internal int for the language</td>

</tr>

<tr class="alternateColor">

<td class="indent1">leechers</td>

<td>int</td>

<td>number of leechers</td>

</tr>

<tr class="alternateColor">

<td class="indent1">main_cat</td>

<td>int</td>

<td>the main category id this is in.  
13 = AudioBooks  
14 = E-Books  
15 = Musicology  
16 = Radio</td>

</tr>

<tr class="alternateColor">

<td class="indent1">narrator_info</td>

<td>string</td>

<td>json object of id:name pairs</td>

</tr>

<tr class="alternateColor">

<td class="indent1">numfiles</td>

<td>int</td>

<td>number of files in the torrent</td>

</tr>

<tr class="alternateColor">

<td class="indent1">owner</td>

<td>int</td>

<td>userid of the uploader</td>

</tr>

<tr class="alternateColor">

<td class="indent1">owner_name</td>

<td>string</td>

<td>username of the uploader</td>

</tr>

<tr class="alternateColor">

<td class="indent1">seeders</td>

<td>int</td>

<td>number of seeders</td>

</tr>

<tr class="alternateColor">

<td class="indent1">series_info</td>

<td>string</td>

<td>json object of id:name pairs</td>

</tr>

<tr class="alternateColor">

<td class="indent1">size</td>

<td>string</td>

<td>Size of the torrent</td>

</tr>

<tr class="alternateColor">

<td class="indent1">tags</td>

<td>string</td>

<td></td>

</tr>

<tr class="alternateColor">

<td class="indent1">times_completed</td>

<td>int</td>

<td>number of users who have fully snatched the torrent</td>

</tr>

<tr class="alternateColor">

<td class="indent1">title</td>

<td>string</td>

<td></td>

</tr>

<tr class="alternateColor">

<td class="indent1">vip</td>

<td>boolean</td>

<td>if the item is vip or not</td>

</tr>

<tr class="alternateColor">

<td>total</td>

<td>int</td>

<td>the number of results the server loaded for your search. Automatically expands as you ask for later results</td>

</tr>

<tr class="alternateColor">

<td>total_found</td>

<td>int</td>

<td>Total results found</td>

</tr>

</tbody>

</table>

**Comment by jeff47** [comment]
I was afraid this might be the case - I checked the forums and unless things have changed, MAM's API is one the primitive side.

**Comment by DreadDragoon** [comment]
+1, 

for fl and fl_vip

**Comment by jeff47** [comment]
Probably not going to happen, after talking with folks at MAM.  They don't really want people using things like Prowlarr.

**Comment by DreadDragoon** [comment]
Well, its in the API... one could easily fork and add it.. its a really easy call, heh

**Comment by DreadDragoon** [comment]
> Based on MAM's API (see below) it does not appear they have a method to trigger the use of a freeleech token (or even search freeleech only on a similarly related note).
> 
> ## @ta264 see anything I'm missing?
> # Torrent Search (JSON)
> ## URI: /tor/js/loadSearchJSONbasic.php
> ### Search torrents
> main site search, returning json results (instead of html). This endpoint can accept input via post as application/xml, application/json, multipart/form-data, or application/x-www-form-urlencoded, as well as via get
> 
> Parameter	Data type	Additional information
> description	empty	If this parameter is set, it will display the full description field for the torrent.
> dlLink	blank	show hash for dl link (prepend https://www.myanonamouse.net/tor/download.php/ to use) for downloading on something without a session cookie. Alternatively use session cookie and just hit https://www.myanonamouse.net/tor/download.php?tid=# replacing # with the id number.
> perpage	int	int in range of 5 to 100, telling how many results to return
> thumbnail	Set	If this value is set, will return the thumbnail url.
> tor	array	
> ### REQUIRED
> cat	list	List of integers for the categories you wish to view in results
> endDate	date	Date in format YYYY-MM-DD or unix timestamp torrents shoujld have been created before. Exclusive of value provided
> hash	HEX string	Hexadecimal encoded hash from a torrent
> main_cat	array	Array of ID(s) of the main category to include. IDs are: 13 AudioBooks 14 E-Books 15 Musicology 16 Radio
> searchIn	Enum	list to come
> searchType	enum	'titleAsc': By the Title, Descending order 'titleDesc': By the Title, Ascending order 'fileAsc': By number of files, Ascending Order 'fileDesc': By number of files, Descending Order 'sizeAsc': By size of the torrent, Ascending Order 'sizeDesc': By size of the torrent, Descending Order 'seedersAsc': By number of Seeders, Ascending Order 'seedersDesc': By number of Seeders, Descending Order 'leechersAsc': By number of Leechers, Ascending Order 'leechersDesc': By number of Leechers, Descending Order 'snatchedAsc': By number of times snatched, Ascending Order 'snatchedDesc': By number of times snatched, Descending Order 'dateAsc': By Date Added, Ascending Order 'dateDesc': By Date Added, Descending Order 'bmkaAsc': By date bookmarked, Ascending Order (Note: may return odd results if not bookmarked) 'bmkaDesc': By date bookmarked, Descending Order (Note: may return odd results if not bookmarked) 'reseedAsc': Date Reseed Request Added, Ascending Order (Note: may return odd results if no reseed request) 'reseedDesc': Date Reseed Request Added, Descending Order (Note: may return odd results if no reseed request) 'random': random, duh 'default':     If text search present: by weight DESC, then ID desceding,     else if instead searchIn is 'myReseed' or 'allReseed': same as reseedAsc     else if searchIn is Bookmarks: same as 'bmkaDesc'     else same as 'dateDesc'
> sortType	enum	'titleAsc': By the Title, Descending order 'titleDesc': By the Title, Ascending order 'fileAsc': By number of files, Ascending Order 'fileDesc': By number of files, Descending Order 'sizeAsc': By size of the torrent, Ascending Order 'sizeDesc': By size of the torrent, Descending Order 'seedersAsc': By number of Seeders, Ascending Order 'seedersDesc': By number of Seeders, Descending Order 'leechersAsc': By number of Leechers, Ascending Order 'leechersDesc': By number of Leechers, Descending Order 'snatchedAsc': By number of times snatched, Ascending Order 'snatchedDesc': By number of times snatched, Descending Order 'dateAsc': By Date Added, Ascending Order 'dateDesc': By Date Added, Descending Order 'bmkaAsc': By date bookmarked, Ascending Order (Note: may return odd results if not bookmarked) 'bmkaDesc': By date bookmarked, Descending Order (Note: may return odd results if not bookmarked) 'reseedAsc': Date Reseed Request Added, Ascending Order (Note: may return odd results if no reseed request) 'reseedDesc': Date Reseed Request Added, Descending Order (Note: may return odd results if no reseed request) 'categoryAsc': Sorted by category (number) Ascending, followed by title Ascending 'categoryDesc': Sorted by category (number) Descending, followed by title Ascending 'random': random, duh 'default': If text search present: by weight DESC, then ID desceding, else if instead searchIn is 'myReseed' or 'allReseed': same as reseedAsc else if searchIn is Bookmarks: same as 'bmkaDesc' else same as 'dateDesc'
> srchIn	array	
> author	Set	If set, will cause the tor[text] to search in the author
> description	Set	If set, will cause the tor[text] to search in the description
> filenames	Set	If set, will cause the tor[text] to search in the filenames
> fileTypes	Set	If set, will cause the tor[text] to search in the file types
> narrator	Set	If set, will cause the tor[text] to search in the narrator
> series	Set	If set, will cause the tor[text] to search in the series
> tags	Set	If set, will cause the tor[text] to search in the tags
> startDate	date	Date in format YYYY-MM-DD or unix timestamp of earliest torrent(s) to show. Inclusive of the provided value
> startNumber	Int	Number of entries to skip. Used in pagination.
> text	text	Text to search for.
> ### Example input
> application/x-www-form-urlencoded:
> tor%5Bcat%5D%5B%5D=0&tor%5BsortType%5D=default&tor%5BbrowseStart%5D=true&tor%5BstartNumber%5D=0&bannerLink&bookmarks&dlLink&description&tor%5Btext%5D=mp3%20m4a
> 
> JSON:
> 
> {
> 	"tor": {
> 		"text": "collection cookbooks food test kitchen",
> 		"srchIn": {
> 			"title": "true",
> 			"author": "true",
> 			"narrator": "true"
> 		},
> 		"searchType": "all",
> 		"searchIn": "torrents",
> 		"cat": ["0"],
> 		"browseFlagsHideVsShow": "0",
> 		"startDate": "",
> 		"endDate": "",
> 		"hash": "",
> 		"sortType": "default",
> 		"startNumber": "0"
> 	},
> 	"thumbnail": "true"
> }
> ### Output Parameters
> Parameter	Data type	Additional information
> data	List	This is a list of objects/arrays with the following keys
> added	datetime	the date and time (in utc) the item was uploaded to site
> author_info	string	json object of id:name pairs
> bookmarked	datetime (nullable)	Datetime of when an item was bookmarked by the user (or null if not bookmarked)
> browseflags	bitfield	bit field of the different tags and flags on a torrent see [link pending] for more information
> cat	string	the html display for the category based on the users preferences
> category	int	specific category id the item is in
> catname	string	the category the item is in
> comments	int	number of comments users have added to the item
> dl	string	user specific hash to download the torrent file. You can download by appending it to the url: /tor/download.php/
> filetypes	string	concatenated string of file types
> fl_vip	boolean	if the item is freeleech and/or vip
> free	boolean	if the item is freeleech or not
> id	int	the id of the torrent itself. User can pull up the page via /t/{id}
> lang_code	string	the 3 letter ISO code for the language
> language	int	the internal int for the language
> leechers	int	number of leechers
> main_cat	int	the main category id this is in. 13 = AudioBooks 14 = E-Books 15 = Musicology 16 = Radio
> narrator_info	string	json object of id:name pairs
> numfiles	int	number of files in the torrent
> owner	int	userid of the uploader
> owner_name	string	username of the uploader
> seeders	int	number of seeders
> series_info	string	json object of id:name pairs
> size	string	Size of the torrent
> tags	string	
> times_completed	int	number of users who have fully snatched the torrent
> title	string	
> vip	boolean	if the item is vip or not
> total	int	the number of results the server loaded for your search. Automatically expands as you ask for later results
> total_found	int	Total results found

Your input type of searchtype has the metadata for sortype listed, looks like a duplicate line, searchtype can do a few types, currently its using nVIP, so to add VIP, FL, or FL-VIP we'd just need those added as options 

<html>
<body>


searchType | enum | 'all': Search everything'
active': Last update had 1+ seeders'
inactive': Last update has 0 seeders'
fl': Freeleech torrents'
fl-VIP': Freeleech or VIP torrents'
VIP': VIP torrents'
nVIP': Torrents not VIP'
nMeta': Torrents missing meta data (old torrents)
-- | -- | --



</body>
</html>

**Comment by ta264** [comment]
As far as I know there's no way to grab a torrent using a freeleech token via the API.

The selection of freeleech torrents is so small I don't really see the point of allowing you to restrict search to just those.

**Comment by DreadDragoon** [comment]
I'm more about the fl_vip chunk, that way I don't need to use tokens, there
are tons of VIP torrents

**Comment by bakerboy448** [comment]
> I'm more about the fl_vip chunk, that way I don't need to use tokens, there are tons of VIP torrents
> […](#)

That's covered by https://github.com/Prowlarr/Prowlarr/issues/810 not this GHI - which is for using a freeleech token

**Comment by DreadDragoon** [comment]
Yeah, fair point. And looking at the FL token usage mechanism, tokens are
not a valid option.
