### ISSUE TITLE
Postgres Log DB Password Cleanse

### ISSUE THREAD

**Issue by Qstick** [Prowlarr/Prowlarr#632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`[Info] MigrationController: *** Migrating Database=prowlarr-main;Host=postgres14;Username=qstick;Password=qstick;Port=5432;Enlist=False ***`

### Expected Behavior

`[Info] MigrationController: *** Migrating Database=prowlarr-main;Host=postgres14;Username=qstick;Password=(removed);Port=5432;Enlist=False ***`

### Steps To Reproduce

Run Postgress

### Environment

```markdown
- OS: 
- Prowlarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Other (This issue will be closed)

### Anything else?

Nope

[AB#1967](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1967)

**Comment by bakerboy448** [comment]
Still not cleansing 😩

**Comment by obsidiangroup** [comment]
It appears that while the password is removed from the log, it still shows up in the docker logs.  This is possibly because:

 `public void Migrate(string connectionString, MigrationContext migrationContext)
        {
            var sw = Stopwatch.StartNew();
            _logger.Info("*** Migrating {0} ***", connectionString);
`

This is appending the entire connectionString to the log, and connectionString is not being scrubbed beforehand.  Is it required to display the entire connectionString at all?  If so, using SubString or RegEx to remove the Password portion?

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/bfa68347e69a10d10fd56c4912615234a07f7c66

Log files should be cleansed now

Docker logs / console logs are not cleansed
